### ISSUE TITLE
where can I find the "Manual multi-camera calibration" example?

### ISSUE THREAD

**Issue by mundher** [potocpav/python-concur#15]
where can I find the "Manual multi-camera calibration" example?

**Comment by potocpav** [comment]
Unfortunately, nowhere. I will talk about open-sourcing the app with my employer. Right now, I don't have the go-ahead.

Do you want it for the calibration, or just as an example of a non-trivial app?

**Comment by mundher** [comment]
> Do you want it for the calibration, or just as an example of a non-trivial app?

I was wonder how this library can be used in a complex scenario like this.

**Comment by potocpav** [comment]
I may be able to share just the GUI part of the app, will look into that. Don't expect it will be in a few days though :/

**Comment by potocpav** [comment]
Closing in favor of issue #19.
