### ISSUE TITLE
v_slider_float via c.interactive_elem -> Has the 'float power' argument been mistakenly cast to flags? Call function with ImGuiSliderFlags_Logarithmic flags instead.") at imgui-cpp/imgui_widgets.cpp:2754

### ISSUE THREAD

**Issue by chwba** [potocpav/python-concur#24]
Im trying to create a `v_slider_float` I get:
`imgui.core.ImGuiError: ImGui assertion error ((flags == 1 || (flags & ImGuiSliderFlags_InvalidMask_) == 0) && "Invalid ImGuiSliderFlags flag!  Has the 'float power' argument been mistakenly cast to flags? Call function with ImGuiSliderFlags_Logarithmic flags instead.") at imgui-cpp/imgui_widgets.cpp:2754`

I call it via:

```python
c.interactive_elem(imgui.v_slider_float,
                   name="SLIDER_FLOAT",
                   width=20.0, height=100, value=1.0,
                   min_value=1, max_value=10,
                   format="%0.3f",
                   tag='my_tag'),
```

Maybe related to: 
https://github.com/ocornut/imgui/issues/3361

**Comment by potocpav** [comment]
Thanks for the report, and the upstream cause.

I fixed the issue by adapting PyImGui to the changes. It should be fixed in the 1.3.7 release.

You can apply the fix by upgrading python-concur to v0.10.0 - which contains some other changes, or just by upgrading concur_imgui to 1.3.7.

**Comment by potocpav** [comment]
Here is the commit with the fix https://github.com/potocpav/pyimgui/commit/96c60050f5c69866499e44a9792717dac684d6f0

**Comment by chwba** [comment]
Tested, works indeed. How do we either change the position or hide the value inside the slider, it looks odd.

![image](https://user-images.githubusercontent.com/22568014/96338482-aedc3680-108e-11eb-8a00-00ea5b1c8419.png)

**Comment by potocpav** [comment]
Glad you solved it. Improving the docs would indeed be great! The [API documentation](https://potocpav.github.io/python-concur-docs/master/) is generated from source code using the `pdoc3` library (`pip install pdoc3`). For example, [this docstring](https://github.com/potocpav/python-concur/blob/master/concur/widgets.py#L138-L148) creates [this record in the docs](https://potocpav.github.io/python-concur-docs/master/widgets.html#concur.widgets.image_button). For more information, see [the pdoc3 documentation](https://pdoc3.github.io/pdoc/doc/pdoc/#gsc.tab=0) - but it's mostly just markdown.

To improve the docs, just find a relevant function/module, and modify its docstring. Run the `mkdocs.sh` script to test your changes - it updates the HTML documentation in the `doc` folder. You can then create a PR with the change to the `python-concur` repo. I can update `python-concur-docs` using `mkdocs.sh` myself.

If you have documentation which doesn't belong to the API docs, you can create PRs directly in the [python-concur-docs repo](https://github.com/potocpav/python-concur-docs) by, for example, modifying/creating some of the Markdown files.
